export const ROUTER_NAME_LIST = {
  LOGIN_PAGE: 'login',
  HOME_PAGE: 'home',
  USER_PAGE: 'users',
  VEHICLE_PAGE: 'vehicles',
  DESTINATION_PAGE: 'destination',
  DETAIL_DESTINATION_PAGE: 'detail-destination',
  LIST_DESTINATION_PAGE: 'list-destination',
  CREATE_DESTINATION_PAGE: 'create-destination',
  EDIT_DESTINATION_PAGE: 'edit-destination',
  ATTRACTION_CATEGORIES_PAGE: 'attraction-categories',
  ACCOMMODATION_CATEGORIES_PAGE: 'accommodation-categories',
  RESTAURANT_CATEGORIES_PAGE: 'restaurant-categories',
  LIST_ITINERARY_PAGE: 'list-itinerary',
  CREATE_ITINERARY_PAGE: 'create-itinerary',
}
