export const ROUTER_NAME_LIST = {
  LOGIN_PAGE: 'Đăng nhập',
  HOME_PAGE: 'Trang chủ',
  USER_PAGE: 'Người dùng',
  VEHICLE_PAGE: 'Phương tiện',
  DESTINATION_PAGE: 'Địa điểm',
  DETAIL_DESTINATION_PAGE: 'Chi tiết địa điểm',
  LIST_DESTINATION_PAGE: 'Danh sách địa điểm',
  CREATE_DESTINATION_PAGE: 'Tạo địa điểm',
  EDIT_DESTINATION_PAGE: 'Chỉnh sửa địa điểm',
  ATTRACTION_CATEGORIES_PAGE: 'Danh mục điểm tham quan',
  ACCOMMODATION_CATEGORIES_PAGE: 'Danh mục chỗ ở',
  RESTAURANT_CATEGORIES_PAGE: 'Danh mục nhà hàng',
  LIST_ITINERARY_PAGE: 'Danh sách hành trình',
  CREATE_ITINERARY_PAGE: 'Tạo hành trình',
}
