export const URL_LOGIN = '/api/admin/login'
export const URL_LOGOUT = '/api/admin/logout'
export const URL_GET_USERS = '/api/admin/users'
export const URL_CREATE_USER = '/api/admin/users/store'
export const URL_UPDATE_USER = '/api/admin/users/update'
export const URL_DELETE_USER = '/api/admin/users/delete'
